
OBJ	=	gribdataset.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
        cd degrib18 && nmake /NOLOGO /f makefile.vc && cd ..
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj
	-del degrib18\degrib\*.obj
	-del degrib18\g2clib-1.0.4\*.obj

