
GDAL_ROOT	=	..\..

OBJ	=	JPIPKAKDataset.obj
EXTRAFLAGS = 	-I$(KAKDIR)\include /DCORESYS_IMPORTS /DKDU_AUX_IMPORTS /DKDU_PENTIUM_MSVC

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj
	-del *.dll
