
GDAL_ROOT	=	..\..

OBJ	=	JPIPKAKDataset.obj  kdu_cache.obj
EXTRAFLAGS = 	-I$(KAKDIR)\apps\support\ -I$(KAKDIR)\apps\compressed_io\ -I$(KAKDIR)\coresys\common\ /DKDU_PENTIUM_MSVC /GX -I$(KAKDIR)\apps\caching_sources

!INCLUDE $(GDAL_ROOT)\nmake.opt


default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

kdu_cache.cpp:	  $(KAKDIR)\apps\caching_sources\kdu_cache.cpp
	copy $(KAKDIR)\apps\caching_sources\kdu_cache.cpp 

clean:
	-del *.obj
	-del *.dll
