
GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	jp2kakdataset.obj
EXTRAFLAGS = 	-I$(KAKDIR) -I$(KAKDIR)/apps/jp2 -I$(KAKDIR)/apps/compressed_io -I$(KAKDIR)/coresys/common -I$(KAKDIR)/apps/support -I$(KAKDIR)/apps/image -I$(KAKDIR)/apps/kdu_compress /DKDU_PENTIUM_MSVC /GX

default:	$(OBJ) kakinstall
	xcopy /D  /Y *.obj ..\o

kakinstall:
	copy $(KAKDIR)\obj\*.obj ..\o

clean:
	-del *.obj

