
GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	jp2kakdataset.obj
EXTRAFLAGS = 	-I$(KAKDIR) /DCORESYS_IMPORTS /DKDU_AUX_IMPORTS /DKDU_PENTIUM_MSVC

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

